export type Buyer = {
  id: string;
  ownerName?: string;
  name: string;
  phone?: string;
  budgetMin?: number;
  budgetMax?: number;
  budgetText?: string;
  monthlyMax?: number;
  typePrefs?: Array<"매매" | "전세" | "월세">;
  areaPrefsPy?: number[];
  complexPrefs?: string[];
  floors?: string[];
  mustHaves?: string[];
  notes?: string;
  assignedTo?: string;
  assignedToName?: string;
  assignedToEmail?: string;
  status?: "active" | "hold" | "completed" | "archived" | "deleted";
  lastCommentText?: string;
  lastCommentAt?: number;
  lastCommentAuthor?: string;
  createdAt: number;
  updatedAt?: number;
  deletedAt?: number;
  deletedByUid?: string;
  deletedByEmail?: string;
  deletedReason?: string;
};
